blank_issues_enabled: false
contact_links: []

issue_templates:
  - name: Bug Report
    description: "버그 템플릿"
    file: bug_report.md

  - name: Feature Request
    description: "기본 이슈 템플릿"
    file: feature_request.md
